{
 "title": "Pulsar Sinks",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "{cluster=~\".+\"}"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "{namespace=~\".+\"}"
   },
   {
    "name": "fqfn",
    "label": "FQFN",
    "query": "{fqfn=~\".+\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Sink Last Invocation",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "pulsar_sink_last_invocation{cluster=~\"$cluster\", namespace=~\"$namespace\", fqfn=~\"$fqfn\"}",
     "legendFormat": "{{ fqfn }}"
    }
   ]
  },
  {
   "title": "Sinks Exceptions Num",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(pulsar_sink_system_exceptions_total{cluster=~\"$cluster\", namespace=~\"$namespace\", fqfn=~\"$fqfn\"}[5m])",
     "legendFormat": "system exceptions"
    },
    {
     "expr": "irate(pulsar_sink_user_exceptions_total{cluster=~\"$cluster\", namespace=~\"$namespace\", fqfn=~\"$fqfn\"}[5m])",
     "legendFormat": "user exceptions"
    }
   ]
  },
  {
   "title": "Sink process latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "pulsar_sink_process_latency_ms{cluster=~\"$cluster\", namespace=~\"$namespace\", fqfn=~\"$fqfn\"}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "Received Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(pulsar_sink_received_total{cluster=~\"$cluster\", namespace=~\"$namespace\", fqfn=~\"$fqfn\"} [30s])",
     "legendFormat": "receive message numbers"
    }
   ]
  },
  {
   "title": "Processed Successfully Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(pulsar_sink_processed_successfully_total{cluster=~\"$cluster\", namespace=~\"$namespace\", fqfn=~\"$fqfn\"} [30s])",
     "legendFormat": "{{ cluster }}"
    }
   ]
  }
 ]
}